application_id: "922396453916274729"

# Activity type: 0 = Playing, 2 = Listening, 3 = Watching
type: 1

name: "  "

# Images
largeImageKey: "6f2b7b827a694aca39e108bee858e706"

# URL (optional, works only with certain types)
url: "https://www.twitch.tv/forsen"

# Buttons (optional)
buttons:
  - name: "My Guns"
    url: "https://guns.lol/upfe"
  - name: "GitHub Repo"
    url: "https://github.com/"
